spring:
  application:
    name: street-race
  profiles:
    activity: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${BASE_URL:jdbc:mysql://localhost:3306/street_run}
    username: ${BASE_USERNAME:root}
    password: ${BASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:street-run-secret-dev}