spring:
    application:
        name: street-race
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://ep-raspy-bonus-apfremxc-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
        username: neondb_owner
        password: npg_yT2SWuOM4BRw
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

api:
    security:
        token:
            secret: ${JWT_SECRET:street-run-secret-dev}
